name: CTW
version: 1.0.0
depend: [FalconAPI]
main: com.falconetwork.ctw.CTW
description: FalconNetwork's CTW Gamemode.
commands:
  team:
    description: Team command.
    usage: /<command> join/leave [blue/red/green/yellow]
  location:
    descripton: Outputs location.